ROS2 Support (solves #16)
ros-perception/imu_pipeline pull request #17
Opened 2023-01-18 14:05 UTC by splatter96

I updated the package with ROS2 support. For now I only updated the imu_transformer package as this is what I need at the moment and whats probably needed by most in this package.

All test cases still work as expected as the actual math is not touched only the ROS interface.

I've forgone the original approach of supporting both MagneticField and Vector3 messages for the magnetometer input as this is harder to support in ROS2 without the ShapeShifter or something similar and most IMU drivers already adopted the proposed REP 145 to use only MagneticField messages.

2023-01-30 13:51 UTC, splatter96 commented
@tonybaltovski  Could you take a look at this?

2023-01-30 18:09 UTC, tonybaltovski requested changes
LGTM with a minor nit.

2023-01-30 18:09 UTC, tonybaltovski commented on imu_transformer/package.xml
> +  <!--<depend>nodelet</depend>-->
Remove please

2023-01-31 15:33 UTC, tonybaltovski commented
@splatter96 looks good, just that one minor nit.

2023-02-06 10:29 UTC, splatter96 commented on imu_transformer/package.xml
> +  <!--<depend>nodelet</depend>-->
Incorporated the requested change.

2023-02-06 10:32 UTC, tonybaltovski approved these changes

2023-02-06 10:32 UTC, merged